import { createContext, useContext, useState } from 'react'


export const COMPANIES = [
  { en: 'Ayalon', he: 'איילון' },
  { en: 'Altshuler Shaham', he: 'אלטשולר שחם' },
  { en: 'Analyst', he: 'אנליסט' },
  { en: 'Training', he: 'הכשרה' },
  { en: 'The Phoenix', he: 'הפניקס' },
  { en: 'Harel', he: 'הראל' },
  { en: 'Clal', he: 'כלל' },
  { en: 'Migdal', he: 'מגדל' },
  { en: 'Mediho', he: 'מדיהו' },
  { en: 'Mor', he: 'מור' },
  { en: 'Menora', he: 'מנורה' }
];

const LanguageContext = createContext()

export const translations = {
  en: {
    // Header
    insuranceDashboard: 'Gal Amagor System',
    dashboard: 'Dashboard',
    upload: 'Upload',
    insights: 'Insights',
    agentsHeader: 'Agents',
    logout: 'Logout',
    
    // Login Page
    welcome: 'Welcome',
    signInAccess: 'Sign in to access your dashboard',
    emailAddress: 'Email Address',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    signIn: 'Sign In',
    needHelp: 'Need help?',
    contactSupport: 'Contact Support',
    simplifyAnalytics: 'Simplify Your Insurance Analytics',
    trackPerformance: 'Track performance, generate reports, and manage your insurance data all in one place.',
    activeAgents: 'Active Agents',
    policies: 'Policies',
    satisfaction: 'Satisfaction',
    
    // Dashboard
    realTimeActivity: 'Real-time activity and updates overview',
    filterByCompany: 'Filter by Company',
    filterByMonth: 'Filter by Month',
    allCompanies: 'All Companies',
    quickStatsMonth: 'Quick Stats - This Month',
    totalOutput: 'Total Output',
    policiesSold: 'Policies sold across all products',
    activeAgentsCount: 'Active Agents',
    uploadProgress: 'Upload Progress',
    thisMonth: 'This month',
    currentlyActive: 'Currently active',
    todaySummary: "Today's Summary",
    policiesAdded: 'Policies Added',
    totalPremium: 'Total Premium',
    agentsActive: 'Agents Active',
    reportsGenerated: 'Reports Generated',
    recentActivities: 'Recent Activities',
    notificationsAlerts: 'Notifications & Alerts',
    pendingActions: 'Pending Actions',
    uploadCSVFiles: 'Upload CSV Files',
    uploadProcess: 'Upload and process your insurance data files for analysis',
    viewInsights: 'View Insights',
    exploreAnalytics: 'Explore detailed analytics and performance metrics',
    
    // Upload Page
    confirmDeleteMessage: 'Are you sure you want to delete this uploaded file? This action cannot be undone.',
    noRecordsFound: 'No records found',
    noFilesFound: 'No uploaded files found',
    tryDifferentFilters: 'Try different filters',
    deleteRecord: 'Delete Record',
    viewDeleteUploadedFiles: 'View & Delete Uploaded Files',
    deleteRecordConfirmation: 'Delete Record Confirmation',
    deleteRecordConfirmationMessage: 'Are you sure you want to delete this record? This action cannot be undone.',
    deleteRecordConfirmationButton: 'Delete',
    deleteRecordConfirmationCancel: 'Cancel',
    selectRecordToDelete: 'Select a record to delete from the system',
    selectFileToDelete: 'Select an uploaded file to delete from the system',
    close: 'Close',
    company: 'Company',
    month: 'Month',
    rows: 'Rows',
    uploadExcelFiles: 'Upload Excel Files',
    uploadCompanyData: 'Upload company data for analysis',
    error: 'Error',
    success: 'Success',
    step1SelectCompanyMonth: 'Step 1: Select Company and Month',
    selectCompany: 'Select Company',
    selectMonth: 'Select Month',
    chooseCompany: 'Choose a company...',
    step2UploadExcel: 'Step 2: Upload Excel File',
    dropFileHere: 'Drop file here',
    uploadExcelFile: 'Upload Excel File',
    dragAndDropBrowse: 'Drag and drop or click to browse',
    excelSupported: '.xlsx and .xlsb supported',
    emptyFileWarning: 'Warning: This Excel file appears to be empty. You can still upload it for tracking purposes.',
    uploadingProcessing: 'Uploading and processing...',
    uploadedFile: 'Uploaded File',
    uploadedSuccessfully: 'Uploaded Successfully',
    uploadFailed: 'Upload Failed',
    processing: 'Processing...',
    submitDataFor: 'Submit Data for',
    selectedCompany: 'Selected Company',
    pleaseSelectCompany: 'Please select a company',
    pleaseUploadExcelFile: 'Please upload an Excel file',
    readyToSubmit: 'Ready to submit for',
    recordAlreadyExists: 'Record Already Exists',
    cannotUploadRecordExists: 'Cannot upload: A record already exists for this company and month. Please delete it first.',
    deleteExistingRecord: 'Delete Existing Record',
    directAgents: 'Yahaloma Agents',
    directAgentsModalTitle: 'Upload Yahaloma Agents Excel File',
    directAgentsModalDescription: 'Upload an Excel file containing Yahaloma agents data',
    selectExcelFile: 'Select Excel File',
    uploadFile: 'Upload File',
    dragDropExcel: 'Drag and drop an Excel file here, or click to browse',
    supportedFormats: 'Supported formats: .xlsx, .xlsb',
    regularElementary: 'Regular Elementary',
    directAgentsTab: 'Yahaloma Agents',
    companiesAffected: 'Companies Affected',
    uploadedOn: 'Uploaded On',

    // Insights Page
    analyticsInsights: 'Analytics & Insights',
    comprehensiveMetrics: 'Comprehensive performance metrics and analytics dashboard',
    exportToCSV: 'Export to CSV',
    activeFilters: 'Active Filters:',
    pension: 'Pension',
    risk: 'Risk',
    financial: 'Financial',
    pensionTransfer: 'Pension Transfer',
    quickStats: 'Quick Stats',
    totalCommission: 'Total Commission',
    totalAmount: 'Total Amount',
    agentsWithSales: 'Agents with Sales',
    totalPolicies: 'Total Policies',
    endMonth: 'End Month',
    department: 'Department',
    inspector: 'Inspector',
    agent: 'Agent',
    allDepartments: 'All Departments',
    allInspectors: 'All Inspectors',
    inspector1: 'Yossi Aviv',
    inspector2: 'Eran Gironi',
    inspector3: 'Itay Eden',
    inspector4: 'Unsupervised', 
    allAgents: 'All Agents',
    allProducts: 'All Products',
    productType: 'Product Type',
    productTypes: 'Product Types',
    startMonth: 'Start Month',
    totalIncome: 'Total Income',
    totalIncomeByAgents: 'Total Income by Agents',
    totalIncomeByDepartments: 'Total Income by Departments',
    totalIncomeByProducts: 'Total Income by Products',
    agentPerformance: 'Agent Performance',
    selectCompanyToEdit: 'Please select a specific company to enable editing',
    editData: 'Edit Data',

    // Targets Page
    targets: 'Targets',
    seasonalityTargets: 'Seasonality Targets Year',
    monthlyTarget: 'Monthly',
    cumulativeTarget: 'Cumulative',
    grandTotal: 'Grand Total',
    year: 'Year',
    selectYear: 'Select Year',
    editTargets: 'Edit Targets',
    saveTargets: 'Save Targets',
    cancelEdit: 'Cancel',
    targetsSavedSuccess: 'Targets saved successfully!',

    // Agents Page
    classification: 'Classification',
    enterClassification: 'Enter classification',
    email: 'Email',
  phone: 'Phone',
  category: 'Category',
  departmentElementary: 'Department - Elementary',
  departmentLifeInsurance: 'Department - Life Insurance',
  enterDepartmentElementary: 'Enter department - elementary',
  enterDepartmentLifeInsurance: 'Enter department - life insurance',
  selectDepartmentLifeInsurance: 'Select department - life insurance',
  selectDepartmentElementary: 'Select department - elementary',
  departmentYashirim: 'ישירים',
  departmentSochnim: 'סוכנים',
  departmentPremium: 'פרמיום',
  departmentShutafim: 'שותפים',
  departmentSochnimYahaloma: 'סוכנים יהלומה',
  departmentChavrotShutafotYahaloma: 'חברות שותפות יהלומה',
  departmentChavrotShutafim: 'חברות שותפים',
  departmentYashirimSigal: 'ישירים סיגל',
  insuranceType: 'Insurance Type',
  status: 'Status',
  currentStatus: 'Current status',
  active: 'Active',
  inactive: 'Inactive',
  employeeGalAmagor: 'Employee in Gal Amagor',
  independentAgent: 'Independent agent',
  formerEmployee: 'Former employee',
  formerIndependentAgent: 'Former independent agent',
  empty: 'Empty',
  lifeInsurance: 'Life Insurance',
  elementary: 'Elementary',
  yes: 'Yes',
  no: 'No',
    clickOnCompanies: 'Click on companies to add or remove them',
    createNewAgentRecord: 'Create a new agent record',
    addAgent: 'Add Agent',
    agentManagement: 'Agent Management',
    manageAgentRecords: 'Manage and update agent records',
    searchAgents: 'Search Agents',
    searchPlaceholder: 'Search by name, number, inspector, or department...',
    clearFilters: 'Clear Filters',
    totalAgents: 'Total Agents',
    filteredResults: 'Filtered Results',
    companies: 'Companies',
    agentList: 'Agent List',
    loading: 'Loading...',
    noAgentsFound: 'No agents found',
    agentName: 'Agent Name',
    agentNumber: 'Agent Number',
    actions: 'Actions',
    update: 'Update',
    delete: 'Delete',
    showing: 'Showing',
    of: 'of',
    agents: 'agents',
    confirmDelete: 'Confirm Delete',
    thisActionCannotBeUndone: 'This action cannot be undone',
    cancel: 'Cancel',
    deleteAgent: 'Delete Agent',
    updateAgent: 'Update Agent',
    editAgentInformation: 'Edit agent information',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    updatingAgent: 'Updating Agent...',
    reAggregatingData: 'Re-aggregating data for affected companies. This may take a moment.',
    agentNameRequired: 'Agent name is required',

    ayalonAgentId: 'Ayalon Agent ID',
    harelAgentId: 'Harel Agent ID',
    migdalAgentId: 'Migdal Agent ID',
    menorahAgentId: 'Menorah Agent ID',
    phoenixAgentId: 'Phoenix Agent ID',
    clalAgentId: 'Clal Agent ID',
    altshulerAgentId: 'Altshuler Agent ID',
    hachsharaAgentId: 'Hachshara Agent ID',
    morAgentId: 'Mor Agent ID',
    medihoAgentId: 'Mediho Agent ID',
    analystAgentName: 'Analyst Agent Name',
    ayalonId: 'Ayalon ID',
    harelId: 'Harel ID',
    migdalId: 'Migdal ID',
    menorahId: 'Menorah ID',
    phoenixId: 'Phoenix ID',
    clalId: 'Clal ID',
    altshulerId: 'Altshuler ID',
    hachsharaId: 'Hachshara ID',
    morId: 'Mor ID',
    medihoId: 'Mediho ID',
    analystName: 'Analyst Name',
    companySpecificAgentIds: 'Agent ID דוחות תפוקה',
    elementaryAgentIds: 'Agent ID אלמנטרי',
    ayalonElementaryId: 'Ayalon Elementary ID',
    hachsharaElementaryId: 'Hachshara Elementary ID',
    harelElementaryId: 'Harel Elementary ID',
    clalElementaryId: 'Clal Elementary ID',
    migdalElementaryId: 'Migdal Elementary ID',
    menorahElementaryId: 'Menorah Elementary ID',
    phoenixElementaryId: 'Phoenix Elementary ID',
    shomeraElementaryId: 'Shomera Elementary ID',
    shlomoElementaryId: 'Shlomo Elementary ID',
    shirbitElementaryId: 'Shirbit Elementary ID',
    haklaiElementaryId: 'Haklai Elementary ID',
    mmsElementaryId: 'MMS Elementary ID',
    kashElementaryId: 'Kash Elementary ID',
    passportElementaryId: 'Passport Elementary ID',
    cooperNinovaElementaryId: 'Cooper Ninova Elementary ID',
    securitiesElementaryId: 'Securities Elementary ID',
    ayalonElementaryPlaceholder: 'Enter Ayalon Elementary ID',
    hachsharaElementaryPlaceholder: 'Enter Hachshara Elementary ID',
    harelElementaryPlaceholder: 'Enter Harel Elementary ID',
    clalElementaryPlaceholder: 'Enter Clal Elementary ID',
    migdalElementaryPlaceholder: 'Enter Migdal Elementary ID',
    menorahElementaryPlaceholder: 'Enter Menorah Elementary ID',
    phoenixElementaryPlaceholder: 'Enter Phoenix Elementary ID',
    shomeraElementaryPlaceholder: 'Enter Shomera Elementary ID',
    shlomoElementaryPlaceholder: 'Enter Shlomo Elementary ID',
    shirbitElementaryPlaceholder: 'Enter Shirbit Elementary ID',
    haklaiElementaryPlaceholder: 'Enter Haklai Elementary ID',
    mmsElementaryPlaceholder: 'Enter MMS Elementary ID',
    kashElementaryPlaceholder: 'Enter Kash Elementary ID',
    passportElementaryPlaceholder: 'Enter Passport Elementary ID',
    cooperNinovaElementaryPlaceholder: 'Enter Cooper Ninova Elementary ID',
    securitiesElementaryPlaceholder: 'Enter Securities Elementary ID',
    enterCategory: 'Enter category',
    enterInsuranceType: 'Enter insurance type',
    enterInspectorName: 'Enter inspector name',
    enterDepartment: 'Enter department',
    enterEmail: 'Enter email',
    enterAgentNumber: 'Enter agent number',
    enterAgentName: 'Enter agent name',
    enterPhone: 'Enter phone',
    ayalonCommissionId: 'Ayalon Commission ID',
    phoenixCommissionId: 'Phoenix Commission ID',
    harelCommissionId: 'Harel Commission ID',
    clalCommissionId: 'Clal Commission ID',
    migdalCommissionId: 'Migdal Commission ID',
    menorahCommissionId: 'Menorah Commission ID',
    passportcardCommissionId: 'Passportcard Commission Name',
    altshulerCommissionId: 'Altshuler Commission ID',
    excellenceCommissionId: 'Excellence Commission ID',
    hachsharaCommissionId: 'Hachshara Commission ID',
    medihoCommissionId: 'Mediho Commission Name',
    morCommissionId: 'Mor Commission ID',
    analystCommissionId: 'Analyst Commission ID',
    ayalonCommissionPlaceholder: 'Enter Ayalon Commission ID',
    phoenixCommissionPlaceholder: 'Enter Phoenix Commission ID',
    harelCommissionPlaceholder: 'Enter Harel Commission ID',
    clalCommissionPlaceholder: 'Enter Clal Commission ID',
    migdalCommissionPlaceholder: 'Enter Migdal Commission ID',
    menorahCommissionPlaceholder: 'Enter Menorah Commission ID',
    passportcardCommissionPlaceholder: 'Enter Passportcard Commission Name',
    altshulerCommissionPlaceholder: 'Enter Altshuler Commission ID',
    excellenceCommissionPlaceholder: 'Enter Excellence Commission ID',
    hachsharaCommissionPlaceholder: 'Enter Hachshara Commission ID',
    medihoCommissionPlaceholder: 'Enter Mediho Commission Name',
    morCommissionPlaceholder: 'Enter Mor Commission ID',
    analystCommissionPlaceholder: 'Enter Analyst Commission ID',
    multipleIdsFormat: 'For multiple IDs, use format: 123,456,789 (no spaces after comma)',
  },
  he: {
    // Header
    insuranceDashboard: 'הסיסטם של גל אלמגור',
    dashboard: 'לוח בקרה',
    upload: 'העלאה',
    insights: 'תובנות',
    agentsHeader: 'סוכנים',
    logout: 'התנתק',
    
    // Login Page
    welcome: 'ברוכים הבאים',
    signInAccess: 'היכנס כדי לגשת ללוח המחוונים שלך',
    emailAddress: 'כתובת אימייל',
    password: 'סיסמה',
    rememberMe: 'זכור אותי',
    forgotPassword: 'שכחת סיסמה?',
    signIn: 'כניסה',
    needHelp: 'צריך עזרה?',
    contactSupport: 'צור קשר עם התמיכה',
    simplifyAnalytics: 'פשט את ניתוח הביטוח שלך',
    trackPerformance: 'עקוב אחר ביצועים, צור דוחות ונהל את נתוני הביטוח שלך במקום אחד.',
    activeAgents: 'סוכנים פעילים',
    policies: 'פוליסות',
    satisfaction: 'שביעות רצון',
    
    // Dashboard
    realTimeActivity: 'סקירה כללית של פעילות ועדכונים בזמן אמת',
    filterByCompany: 'סינון לפי חברה',
    filterByMonth: 'סינון לפי חודש',
    allCompanies: 'כל החברות',
    quickStatsMonth: 'סטטיסטיקות מהירות - חודש זה',
    totalOutput: 'תפוקה כוללת',
    policiesSold: 'פוליסות שנמכרו בכלל המוצרים',
    activeAgentsCount: 'סוכנים פעילים',
    uploadProgress: 'התקדמות העלאה',
    thisMonth: 'החודש',
    currentlyActive: 'פעיל כעת',
    todaySummary: 'סיכום היום',
    policiesAdded: 'פוליסות שנוספו',
    totalPremium: 'פרמיה כוללת',
    agentsActive: 'סוכנים פעילים',
    reportsGenerated: 'דוחות שנוצרו',
    recentActivities: 'פעילויות אחרונות',
    notificationsAlerts: 'התראות ועדכונים',
    pendingActions: 'פעולות ממתינות',
    uploadCSVFiles: 'העלה קבצי CSV',
    uploadProcess: 'העלה ועבד את קבצי נתוני הביטוח שלך לניתוח',
    viewInsights: 'צפה בתובנות',
    exploreAnalytics: 'חקור ניתוחים מפורטים ומדדי ביצועים',
    
    // Upload Page
    confirmDeleteMessage: 'האם אתה בטוח שברצונך למחוק את הקובץ? פעולה זו אינה הפיכה.',
    noRecordsFound: 'לא נמצאו רשומות',
    noFilesFound: 'לא נמצאו קבצים שהועלו',
    tryDifferentFilters: 'נסה לשנות את המסננים',
    deleteRecord: 'מחק רשומה',
    viewDeleteUploadedFiles: 'צפה ומחק קבצים שהועלו',
    deleteRecordConfirmation: 'אישור מחיקה',
    deleteRecordConfirmationMessage: 'האם אתה בטוח שברצונך למחוק את הרשומה?',
    deleteRecordConfirmationButton: 'מחק',
    deleteRecordConfirmationCancel: 'ביטול',
    uploadExcelFiles: 'העלאת קבצי Excel',
    selectRecordToDelete: 'בחר רשומה למחיקה מהמערכת',
    selectFileToDelete: 'בחר קובץ שהועלה למחיקה מהמערכת',
    close: 'סגור',
    company: 'חברה',
    month: 'חודש',
    rows: 'שורות',
    uploadCompanyData: 'העלה נתוני חברה לניתוח',
    error: 'שגיאה',
    success: 'הצלחה',
    step1SelectCompanyMonth: 'שלב 1: בחר חברה וחודש',
    selectCompany: 'בחר חברה',
    selectMonth: 'בחר חודש',
    chooseCompany: 'בחר חברה...',
    step2UploadExcel: 'שלב 2: העלה קובץ Excel',
    dropFileHere: 'שחרר את הקובץ כאן',
    uploadExcelFile: 'העלה קובץ Excel',
    dragAndDropBrowse: 'גרור ושחרר או לחץ לעיון',
    excelSupported: 'תומך ב-.xlsx וב-.xlsb',
    emptyFileWarning: 'אזהרה: קובץ Excel זה נראה ריק. ניתן עדיין להעלות אותו למטרות מעקב.',
    uploadingProcessing: 'מעלה ומעבד...',
    uploadedFile: 'קובץ שהועלה',
    uploadedSuccessfully: 'הועלה בהצלחה',
    uploadFailed: 'ההעלאה נכשלה',
    processing: 'מעבד...',
    submitDataFor: 'שלח נתונים עבור',
    selectedCompany: 'חברה נבחרת',
    pleaseSelectCompany: 'אנא בחר חברה',
    pleaseUploadExcelFile: 'אנא העלה קובץ Excel',
    readyToSubmit: 'מוכן לשליחה עבור',
    recordAlreadyExists: 'רשומה כבר קיימת',
    cannotUploadRecordExists: 'לא ניתן להעלות: רשומה כבר קיימת עבור חברה וחודש זה. יש למחוק אותה תחילה.',
    deleteExistingRecord: 'מחק רשומה קיימת',
    directAgents: 'סוכני יהלומה',
    directAgentsModalTitle: 'העלאת קובץ Excel של סוכני יהלומה',
    directAgentsModalDescription: 'העלה קובץ Excel המכיל נתוני סוכני יהלומה',
    selectExcelFile: 'בחר קובץ Excel',
    uploadFile: 'העלה קובץ',
    dragDropExcel: 'גרור ושחרר קובץ Excel כאן, או לחץ לעיון',
    supportedFormats: 'פורמטים נתמכים: .xlsx, .xlsb',
    regularElementary: 'אלמנטרי רגיל',
    directAgentsTab: 'סוכני יהלומה',
    companiesAffected: 'חברות מושפעות',
    uploadedOn: 'הועלה ב',

    // Insights Page
    analyticsInsights: 'ניתוחים ותובנות',
    comprehensiveMetrics: 'לוח מחוונים מקיף של מדדי ביצועים וניתוחים',
    exportToCSV: 'ייצא ל-CSV',
    activeFilters: 'מסננים פעילים:',
    pension: 'פנסיוני',
    risk: 'סיכונים',
    financial: 'פיננסים',
    pensionTransfer: 'ניודי פנסיה',
    quickStats: 'סטטיסטיקות מהירות',
    totalCommission: 'סה"כ דמי',
    agentsWithSales: 'סוכנים עם מכירות',
    totalPolicies: 'סה"כ פוליסות',
    endMonth: 'חודש סיום',
    department: 'מחלקה',
    inspector: 'מפקח',
    agent: 'סוכן',
    allDepartments: 'כל המחלקות',
    allInspectors: 'כל המפקחים',
    inspector1: 'יוסי אביב',
    inspector2: 'ערן גירוני',
    inspector3: 'איתי אדן',
    inspector4: 'לא מפוקחים', 
    allAgents: 'כל הסוכנים',
    allProducts: 'כל המוצרים',
    productType: 'סוג מוצר',
    productTypes: 'סוגי מוצרים',
    startMonth: 'חודש התחלה',
    totalIncome: 'הכנסה כוללת',
    totalIncomeByAgents: 'הכנסה על ידי סוכנים',
    totalIncomeByDepartments: 'הכנסה על ידי מחלקות',
    totalIncomeByProducts: 'הכנסה על ידי מוצרים',
    agentPerformance: 'ביצוע סוכן',
    selectCompanyToEdit: 'אנא בחר חברה ספציפית כדי לאפשר עריכה',
    editData: 'ערוך נתונים',

    // Targets Page
    targets: 'יעדים',
    seasonalityTargets: 'עונתיות יעדי שנת',
    monthlyTarget: 'חודשי',
    cumulativeTarget: 'מצטבר',
    grandTotal: 'סה"כ',
    year: 'שנה',
    selectYear: 'בחר שנה',
    editTargets: 'ערוך יעדים',
    saveTargets: 'שמור יעדים',
    cancelEdit: 'ביטול',
    targetsSavedSuccess: 'היעדים נשמרו בהצלחה!',

    // Agents Page
    classification: 'קידום',
    email: 'אימייל',
    phone: 'טלפון',
    category: 'קטגוריה',
    departmentElementary: 'מחלקה - אלמנטרי',
    departmentLifeInsurance: 'מחלקה - ביטוח חיים',
    enterDepartmentElementary: 'הזן מחלקה - אלמנטרי',
    enterDepartmentLifeInsurance: 'הזן מחלקה - ביטוח חיים',
    selectDepartmentLifeInsurance: 'בחר מחלקה - ביטוח חיים',
    selectDepartmentElementary: 'בחר מחלקה - אלמנטרי',
    departmentYashirim: 'ישירים',
    departmentSochnim: 'סוכנים',
    departmentPremium: 'פרמיום',
    departmentShutafim: 'שותפים',
    departmentSochnimYahaloma: 'סוכנים יהלומה',
    departmentChavrotShutafotYahaloma: 'חברות שותפות יהלומה',
    departmentChavrotShutafim: 'חברות שותפים',
    departmentYashirimSigal: 'ישירים סיגל',
    insuranceType: 'סוג ביטוח',
    status: 'מצב',
    currentStatus: 'סטטוס עדכני',
    active: 'פעיל',
    inactive: 'לא פעיל',
    employeeGalAmagor: 'עובד בגל אלמגור',
    independentAgent: 'סוכן עצמאי',
    formerEmployee: 'עובד לשעבר',
    formerIndependentAgent: 'סוכן עצמאי לשעבר',
    empty: 'ריק',
    lifeInsurance: 'ביטוח חיים',
    elementary: 'אלמנטרי',
    yes: 'כן',
    no: 'לא',
    clickOnCompanies: 'לחץ על חברות כדי להוסיף או להסיר אותן',
    createNewAgentRecord: 'צור רשומת סוכן חדשה',
    addAgent: 'הוסף סוכן',
    agentManagement: 'ניהול סוכנים',
    manageAgentRecords: 'נהל ועדכן רישומי סוכנים',
    searchAgents: 'חיפוש סוכנים',
    searchPlaceholder: 'חפש לפי שם, מספר, מפקח או מחלקה...',
    clearFilters: 'נקה מסננים',
    totalAgents: 'סה"כ סוכנים',
    filteredResults: 'תוצאות מסוננות',
    companies: 'חברות',
    agentList: 'רשימת סוכנים',
    loading: 'טוען...',
    noAgentsFound: 'לא נמצאו סוכנים',
    agentName: 'שם הסוכן',
    agentNumber: 'מספר סוכן',
    actions: 'פעולות',
    update: 'עדכן',
    delete: 'מחק',
    showing: 'מציג',
    of: 'מתוך',
    agents: 'סוכנים',
    confirmDelete: 'אשר מחיקה',
    thisActionCannotBeUndone: 'פעולה זו אינה הפיכה',
    cancel: 'ביטול',
    deleteAgent: 'מחק סוכן',
    updateAgent: 'עדכן סוכן',
    editAgentInformation: 'ערוך מידע על הסוכן',
    saveChanges: 'שמור שינויים',
    saving: 'שומר...',
    updatingAgent: 'מעדכן סוכן...',
    reAggregatingData: 'מצבר מחדש נתונים עבור חברות מושפעות. זה עשוי לקחת רגע.',
    agentNameRequired: 'שם הסוכן הוא שדה חובה',
    ayalonAgentId: 'מספר סוכן איילון',
    harelAgentId: 'מספר סוכן הראל',
    migdalAgentId: 'מספר סוכן מגדל',
    menorahAgentId: 'מספר סוכן מנורה',
    phoenixAgentId: 'מספר סוכן הפניקס',
    clalAgentId: 'מספר סוכן כלל',
    altshulerAgentId: 'מספר סוכן אלטשולר',
    hachsharaAgentId: 'מספר סוכן חכשרה',
    morAgentId: 'מספר סוכן מור',
    medihoAgentId: 'מספר סוכן מדיהו',
    analystAgentName: 'מספר סוכן אנליסט',
    ayalonId: 'איילון ID',
    harelId: 'הראל ID',
    migdalId: 'מגדל ID',
    menorahId: 'מנורה ID',
    phoenixId: 'הפניקס ID',
    clalId: 'כלל ID',
    altshulerId: 'אלטשולר ID',
    hachsharaId: 'חכשרה ID',
    morId: 'מור ID',
    medihoId: 'מדיהו ID',
    analystName: 'אנליסט שם',
    companySpecificAgentIds: 'Agent ID דוחות תפוקה',
    elementaryAgentIds: 'Agent ID אלמנטרי',
    ayalonElementaryId: 'מספר אלמנטרי איילון',
    hachsharaElementaryId: 'מספר אלמנטרי הכשרה',
    harelElementaryId: 'מספר אלמנטרי הראל',
    clalElementaryId: 'מספר אלמנטרי כלל',
    migdalElementaryId: 'מספר אלמנטרי מגדל',
    menorahElementaryId: 'מספר אלמנטרי מנורה',
    phoenixElementaryId: 'מספר אלמנטרי הפניקס',
    shomeraElementaryId: 'מספר אלמנטרי שומרה',
    shlomoElementaryId: 'מספר אלמנטרי שלמה',
    shirbitElementaryId: 'מספר אלמנטרי שירביט',
    haklaiElementaryId: 'מספר אלמנטרי חקלאית',
    mmsElementaryId: 'מספר אלמנטרי ממסי',
    kashElementaryId: 'מספר אלמנטרי כש',
    passportElementaryId: 'מספר אלמנטרי פספורט',
    cooperNinovaElementaryId: 'מספר אלמנטרי קופר נינובה',
    securitiesElementaryId: 'מספר אלמנטרי סקוריטס',
    ayalonElementaryPlaceholder: 'הזן מספר אלמנטרי איילון',
    hachsharaElementaryPlaceholder: 'הזן מספר אלמנטרי הכשרה',
    harelElementaryPlaceholder: 'הזן מספר אלמנטרי הראל',
    clalElementaryPlaceholder: 'הזן מספר אלמנטרי כלל',
    migdalElementaryPlaceholder: 'הזן מספר אלמנטרי מגדל',
    menorahElementaryPlaceholder: 'הזן מספר אלמנטרי מנורה',
    phoenixElementaryPlaceholder: 'הזן מספר אלמנטרי הפניקס',
    shomeraElementaryPlaceholder: 'הזן מספר אלמנטרי שומרה',
    shlomoElementaryPlaceholder: 'הזן מספר אלמנטרי שלמה',
    shirbitElementaryPlaceholder: 'הזן מספר אלמנטרי שירביט',
    haklaiElementaryPlaceholder: 'הזן מספר אלמנטרי חקלאית',
    mmsElementaryPlaceholder: 'הזן מספר אלמנטרי ממסי',
    kashElementaryPlaceholder: 'הזן מספר אלמנטרי כש',
    passportElementaryPlaceholder: 'הזן מספר אלמנטרי פספורט',
    cooperNinovaElementaryPlaceholder: 'הזן מספר אלמנטרי קופר נינובה',
    securitiesElementaryPlaceholder: 'הזן מספר אלמנטרי סקוריטס',
    enterCategory: 'הזן קטגוריה',
    enterInsuranceType: 'הזן סוג ביטוח',
    selectInspectorName: 'הזן שם מפקח',
    enterDepartment: 'הזן מחלקה',
    enterEmail: 'הזן אימייל',
    enterAgentNumber: 'הזן מספר סוכן',
    enterAgentName: 'הזן שם סוכן',
    enterPhone: 'הזן טלפון',
    enterClassification: 'הזן קידום',
    ayalonCommissionId: 'מספר דמי איילון',
    phoenixCommissionId: 'מספר דמי הפניקס',
    harelCommissionId: 'מספר דמי הראל',
    clalCommissionId: 'מספר דמי כל',
    migdalCommissionId: 'מספר דמי מגדל',
    menorahCommissionId: 'מספר דמי מנורה',
    passportcardCommissionId: 'שם דמי פספורד קארד',
    altshulerCommissionId: 'מספר דמי אלטשולר',
    excellenceCommissionId: 'מספר דמי ביצוע',
    hachsharaCommissionId: 'מספר דמי חכשרה',
    medihoCommissionId: 'שם דמי מדיהו',
    morCommissionId: 'מספר דמי מור',
    analystCommissionId: 'מספר דמי אנליסט',
    ayalonCommissionPlaceholder: 'הזן מספר דמי איילון',
    phoenixCommissionPlaceholder: 'הזן מספר דמי הפניקס',
    harelCommissionPlaceholder: 'הזן מספר דמי הראל',
    clalCommissionPlaceholder: 'הזן מספר דמי כל',
    migdalCommissionPlaceholder: 'הזן מספר דמי מגדל',
    menorahCommissionPlaceholder: 'הזן מספר דמי מנורה',
    passportcardCommissionPlaceholder: 'הזן שם דמי פספורד קארד',
    altshulerCommissionPlaceholder: 'הזן מספר דמי אלטשולר',
    excellenceCommissionPlaceholder: 'הזן מספר דמי ביצוע',
    hachsharaCommissionPlaceholder: 'הזן מספר דמי חכשרה',
    medihoCommissionPlaceholder: 'הזן שם דמי מדיהו',
    morCommissionPlaceholder: 'הזן מספר דמי מור',
    analystCommissionPlaceholder: 'הזן מספר דמי אנליסט',
    multipleIdsFormat: 'למספר מזהים, השתמש בפורמט: 123,456,789 (ללא רווחים אחרי פסיק)',
  }
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('he')

  const t = (key) => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

