import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export const translations = {
  en: {
    // Header
    insuranceDashboard: 'Insurance Dashboard',
    dashboard: 'Dashboard',
    upload: 'Upload',
    insights: 'Insights',
    logout: 'Logout',
    
    // Login Page
    welcome: 'Welcome',
    signInAccess: 'Sign in to access your dashboard',
    emailAddress: 'Email Address',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    signIn: 'Sign In',
    needHelp: 'Need help?',
    contactSupport: 'Contact Support',
    simplifyAnalytics: 'Simplify Your Insurance Analytics',
    trackPerformance: 'Track performance, generate reports, and manage your insurance data all in one place.',
    activeAgents: 'Active Agents',
    policies: 'Policies',
    satisfaction: 'Satisfaction',
    
    // Dashboard
    realTimeActivity: 'Real-time activity and updates overview',
    filterByCompany: 'Filter by Company',
    filterByMonth: 'Filter by Month',
    allCompanies: 'All Companies',
    quickStatsMonth: 'Quick Stats - This Month',
    totalOutput: 'Total Output',
    policiesSold: 'Policies Sold',
    activeAgentsCount: 'Active Agents',
    uploadProgress: 'Upload Progress',
    thisMonth: 'This month',
    currentlyActive: 'Currently active',
    todaySummary: "Today's Summary",
    policiesAdded: 'Policies Added',
    totalPremium: 'Total Premium',
    agentsActive: 'Agents Active',
    reportsGenerated: 'Reports Generated',
    recentActivities: 'Recent Activities',
    notificationsAlerts: 'Notifications & Alerts',
    pendingActions: 'Pending Actions',
    uploadCSVFiles: 'Upload CSV Files',
    uploadProcess: 'Upload and process your insurance data files for analysis',
    viewInsights: 'View Insights',
    exploreAnalytics: 'Explore detailed analytics and performance metrics',
    
    // Upload Page
    uploadCSVFilesTitle: 'Upload CSV Files',
    uploadForAnalysis: 'Upload your insurance data files for analysis and insights',
    step1: 'Step 1: Select Company & Month',
    selectCompany: 'Select Company',
    selectMonth: 'Select Month',
    chooseCompany: 'Choose a company...',
    step2: 'Step 2: Upload CSV Files',
    dropFiles: 'Drop your files here',
    dragDrop: 'Drag and drop your files here, or click to browse',
    csvFilesOnly: 'CSV files only',
    multipleSupported: 'Multiple files supported',
    uploadingFiles: 'Uploading files...',
    uploadedFiles: 'Uploaded Files',
    files: 'file(s)',
    rows: 'rows',
    uploadedSuccessfully: 'Uploaded successfully',
    clearAllFiles: 'Clear All Files',
    submitDataFor: 'Submit Data for',
    selectedCompany: 'Selected Company',
    pleaseSelectCompany: 'Please select a company to continue',
    pleaseUploadFile: 'Please upload at least one CSV file',
    readyToSubmit: 'Ready to submit',
    
    // Insights Page
    analyticsInsights: 'Analytics & Insights',
    comprehensiveMetrics: 'Comprehensive performance metrics and analytics dashboard',
    exportToCSV: 'Export to CSV',
    activeFilters: 'Active Filters:',
    performanceMetrics: 'Performance Metrics',
    monthlyOutput: 'Monthly Output',
    ytd: 'Year-to-Date (YTD)',
    growthRate: 'Growth Rate',
    targetAchievement: 'Target Achievement',
    policiesCount: 'Policies Count',
    comparisons: 'Comparisons',
    vsLastYear: 'vs Last Year',
    vsLastMonth: 'vs Last Month',
    vsTarget: 'vs Target',
    vsIndustryAvg: 'vs Industry Average',
    yearOverYear: 'Year-over-Year',
    monthOverMonth: 'Month-over-Month',
    aboveTarget: 'Above Target',
    aboveAverage: 'Above Average',
    rankingsPerformance: 'Rankings & Performance',
    topPerformers: 'Top Performers',
    bottomPerformers: 'Bottom Performers',
    mostImproved: 'Most Improved',
    monthlyTrend: 'Monthly Trend',
    breakdownByType: 'Breakdown by Insurance Type',
    statusIndicators: 'Status Indicators',
    onTrack: 'On Track',
    offTrack: 'Off Track',
    belowTarget: 'Below Target',
    positiveGrowth: 'Positive Growth',
    negativeGrowth: 'Negative Growth',
    inactiveAgents: 'Inactive Agents',
    financialOverview: 'Financial Overview',
    totalCommission: 'Total Commission',
    avgPolicyValue: 'Avg Policy Value',
    revenuePerAgent: 'Revenue per Agent',
    alertsHighlights: 'Alerts & Highlights',
    performanceSummary: 'Performance Summary',
    thisQuarter: 'This Quarter',
    thisYear: 'This Year',
    yoyGrowth: 'YoY Growth',
    momGrowth: 'MoM Growth',
  },
  he: {
    // Header
    insuranceDashboard: 'לוח מחוונים לביטוח',
    dashboard: 'לוח בקרה',
    upload: 'העלאה',
    insights: 'תובנות',
    logout: 'התנתק',
    
    // Login Page
    welcome: 'ברוכים הבאים',
    signInAccess: 'היכנס כדי לגשת ללוח המחוונים שלך',
    emailAddress: 'כתובת אימייל',
    password: 'סיסמה',
    rememberMe: 'זכור אותי',
    forgotPassword: 'שכחת סיסמה?',
    signIn: 'כניסה',
    needHelp: 'צריך עזרה?',
    contactSupport: 'צור קשר עם התמיכה',
    simplifyAnalytics: 'פשט את ניתוח הביטוח שלך',
    trackPerformance: 'עקוב אחר ביצועים, צור דוחות ונהל את נתוני הביטוח שלך במקום אחד.',
    activeAgents: 'סוכנים פעילים',
    policies: 'פוליסות',
    satisfaction: 'שביעות רצון',
    
    // Dashboard
    realTimeActivity: 'סקירה כללית של פעילות ועדכונים בזמן אמת',
    filterByCompany: 'סינון לפי חברה',
    filterByMonth: 'סינון לפי חודש',
    allCompanies: 'כל החברות',
    quickStatsMonth: 'סטטיסטיקות מהירות - חודש זה',
    totalOutput: 'תפוקה כוללת',
    policiesSold: 'פוליסות שנמכרו',
    activeAgentsCount: 'סוכנים פעילים',
    uploadProgress: 'התקדמות העלאה',
    thisMonth: 'החודש',
    currentlyActive: 'פעיל כעת',
    todaySummary: 'סיכום היום',
    policiesAdded: 'פוליסות שנוספו',
    totalPremium: 'פרמיה כוללת',
    agentsActive: 'סוכנים פעילים',
    reportsGenerated: 'דוחות שנוצרו',
    recentActivities: 'פעילויות אחרונות',
    notificationsAlerts: 'התראות ועדכונים',
    pendingActions: 'פעולות ממתינות',
    uploadCSVFiles: 'העלה קבצי CSV',
    uploadProcess: 'העלה ועבד את קבצי נתוני הביטוח שלך לניתוח',
    viewInsights: 'צפה בתובנות',
    exploreAnalytics: 'חקור ניתוחים מפורטים ומדדי ביצועים',
    
    // Upload Page
    uploadCSVFilesTitle: 'העלה קבצי CSV',
    uploadForAnalysis: 'העלה את קבצי נתוני הביטוח שלך לניתוח ותובנות',
    step1: 'שלב 1: בחר חברה וחודש',
    selectCompany: 'בחר חברה',
    selectMonth: 'בחר חודש',
    chooseCompany: 'בחר חברה...',
    step2: 'שלב 2: העלה קבצי CSV',
    dropFiles: 'שחרר את הקבצים כאן',
    dragDrop: 'גרור ושחרר את הקבצים שלך כאן, או לחץ לעיון',
    csvFilesOnly: 'קבצי CSV בלבד',
    multipleSupported: 'תמיכה במספר קבצים',
    uploadingFiles: 'מעלה קבצים...',
    uploadedFiles: 'קבצים שהועלו',
    files: 'קבצ(ים)',
    rows: 'שורות',
    uploadedSuccessfully: 'הועלה בהצלחה',
    clearAllFiles: 'נקה את כל הקבצים',
    submitDataFor: 'שלח נתונים עבור',
    selectedCompany: 'חברה נבחרת',
    pleaseSelectCompany: 'אנא בחר חברה כדי להמשיך',
    pleaseUploadFile: 'אנא העלה לפחות קובץ CSV אחד',
    readyToSubmit: 'מוכן לשליחה',
    
    // Insights Page
    analyticsInsights: 'ניתוחים ותובנות',
    comprehensiveMetrics: 'לוח מחוונים מקיף של מדדי ביצועים וניתוחים',
    exportToCSV: 'ייצא ל-CSV',
    activeFilters: 'מסננים פעילים:',
    performanceMetrics: 'מדדי ביצועים',
    monthlyOutput: 'תפוקה חודשית',
    ytd: 'מתחילת השנה (YTD)',
    growthRate: 'שיעור צמיחה',
    targetAchievement: 'השגת יעד',
    policiesCount: 'מספר פוליסות',
    comparisons: 'השוואות',
    vsLastYear: 'לעומת שנה שעברה',
    vsLastMonth: 'לעומת חודש שעבר',
    vsTarget: 'לעומת יעד',
    vsIndustryAvg: 'לעומת ממוצע התעשייה',
    yearOverYear: 'שנה על שנה',
    monthOverMonth: 'חודש על חודש',
    aboveTarget: 'מעל היעד',
    aboveAverage: 'מעל הממוצע',
    rankingsPerformance: 'דירוגים וביצועים',
    topPerformers: 'מובילים',
    bottomPerformers: 'בביצועים נמוכים',
    mostImproved: 'השתפרו הכי הרבה',
    monthlyTrend: 'מגמה חודשית',
    breakdownByType: 'פילוח לפי סוג ביטוח',
    statusIndicators: 'אינדיקטורי סטטוס',
    onTrack: 'במסלול',
    offTrack: 'מחוץ למסלול',
    belowTarget: 'מתחת ליעד',
    positiveGrowth: 'צמיחה חיובית',
    negativeGrowth: 'צמיחה שלילית',
    inactiveAgents: 'סוכנים לא פעילים',
    financialOverview: 'סקירה פיננסית',
    totalCommission: 'עמלה כוללת',
    avgPolicyValue: 'ערך פוליסה ממוצע',
    revenuePerAgent: 'הכנסה לסוכן',
    alertsHighlights: 'התראות ודגשים',
    performanceSummary: 'סיכום ביצועים',
    thisQuarter: 'רבעון זה',
    thisYear: 'שנה זו',
    yoyGrowth: 'צמיחה שנתית',
    momGrowth: 'צמיחה חודשית',
  }
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en')

  const t = (key) => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

